import type { Metadata } from "next";

import "@/app/ui/globals.css";
import { montserrat } from "./ui/fonts";

import Nav from "./ui/Nav/Nav";
import Footer from "./ui/Footer/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.className} antialiased bg-[#121212] text-[#F5F5F5] `}
      >
        {/* responsive Note */}
        <p className=" md:hidden text-lg font-bold absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2">
          We are working about Responsive...
        </p>
        <div className=" hidden md:block">
          <Nav />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
